### ISSUE TITLE
Use a better default display name than "spy"

### ISSUE THREAD

**Issue by papandreou** [unexpectedjs/unexpected-sinon#12]
Currently we use `spy.displayName`, which defaults to "spy" when not stubbing out or spying on an existing function. Sinon populates `spy.id` with 'spy#1', 'spy#2' etc., and it would be better to use that (or a derivative), especially in the `to have calls satisfying` diff where multiple spies are mixed together.

**Comment by papandreou** [comment]
Turns out sinon has a couple of options when it comes to naming spies:

```js
var spy1= sinon.spy(function theSpyName () {});
var spy2 = sinon.spy().named('theOtherSpyName');
```

Started using those here: https://github.com/unexpectedjs/unexpected-sinon/commit/c24fac106d2ee43c24e863effb73d94cc9ae674e

Maybe that's sufficient. We could also look into color-coding the function name so that you'd be able to tell which invocations pertain to the same spies. If the code could automatically pick a color (hue) based on the spy id, it wouldn't require any shared state between `inspect` calls. What do you think?

**Comment by papandreou** [comment]
> We could also look into color-coding the function name ...

That was pretty simple to implement: https://github.com/unexpectedjs/unexpected-sinon/tree/feature/spyColors

Looks rather nice:
![spycolors](https://cloud.githubusercontent.com/assets/373545/9972613/82109522-5e66-11e5-9231-3838fb557520.png)

**Comment by papandreou** [comment]
Increased the contrast a bit:

![spycolorsincreasedcontrast](https://cloud.githubusercontent.com/assets/373545/9972677/6b94071a-5e67-11e5-9b04-39dd4f92f72e.png)

**Comment by sunesimonsen** [comment]
Nice investigation, I like the colors and the naming feature.

**Comment by sunesimonsen** [comment]
I'm a bit reluctant towards adding one-color as a dependency just to get the extra contrast. I don't know why, because the size doesn't really matter.

**Comment by sunesimonsen** [comment]
Mhh it is actually much smaller than I expected.

**Comment by sunesimonsen** [comment]
It would require us to browserify unexpected-sinon for the browser.

**Comment by papandreou** [comment]
Yeah, I agree. We should just make a "cyclic" list of premade colors when we have found a good set. That'll also be much faster.

**Comment by sunesimonsen** [comment]
And fit with the themes.

**Comment by papandreou** [comment]
Switched to a (short) premade list: https://github.com/unexpectedjs/unexpected-sinon/commit/2f4bbb25340584b4a21a44bfac54b82141d95bf5

> And fit with the themes.

What do you mean, exactly? Should we try to make the palette customizable by themes?
