### ISSUE TITLE
Added the `exhaustively` flag to `to have calls satisfying`

### ISSUE THREAD

**Issue by sunesimonsen** [unexpectedjs/unexpected-sinon#22]
http://unexpected.js.org/unexpected-sinon/assertions/array-like/to-have-calls-satisfying/
http://unexpected.js.org/unexpected-sinon/assertions/spy/to-have-calls-satisfying/

**Comment by papandreou** [comment]
Implemented by https://github.com/unexpectedjs/unexpected-sinon/pull/23

**Comment by sunesimonsen** [comment]
Awesome. thanks.
