### ISSUE TITLE
TypeError: Function has non-object prototype 'undefined' in instanceof check

### ISSUE THREAD

**Issue by KeKs0r** [unexpectedjs/unexpected-sinon#38]
Hi,

while trying to validate the arguments a function was called I sometimes run into this error message:

`TypeError: Function has non-object prototype 'undefined' in instanceof check`

My Assertion looks like this:

``` javascript
    const itemsData = {
      '2': { id: 2, name: 'Cheap Product', price: 0.99 },
      '3': { id: 3, name: 'Last Product', price: 11.89 } 
    }
    expect(handlerSpy, 'to have a call satisfying', {
        args: [{ itemsData }],
    });
```

And this is the arguments its actually called with:

```
{ 
  type: 'mock.action',
  items: [ { id: 2, quantity: 2 }, { id: 3, quantity: 1 } ],
  itemsData: [ 
     { id: 2, name: 'Cheap Product', price: 0.99 },
     { id: 3, name: 'Last Product', price: 11.89 } 
  ] 
}
```

So I know why my test is failing, but I think the error message is quite misleading. Not sure if this can be fixed, since one is a array and the other one is an object.

**Comment by andykog** [comment]
Made a PR #38
