### ISSUE TITLE
Documentation wording correction needed

### ISSUE THREAD

**Issue by plroebuck** [unexpectedjs/unexpected-sinon#90]
> Here is an example an example stolen from
[Gary Bernhardt](https://twitter.com/garybernhardt).

Remove "doubled" `an example`.

https://github.com/unexpectedjs/unexpected-sinon/blame/master/documentation/index.md#L24

**Comment by papandreou** [comment]
Thanks -- deployed a fix now 🤗

**Comment by sunesimonsen** [comment]
Thanks, sometimes things run a bit too fast.
